#ifndef __DIRECTIVES_ORDER_H__
#define __DIRECTIVES_ORDER_H__ 1

enum DirectivesOrder {
  CONNECTION_INIT = 1,
  PREPROCESS_REQUEST = 2,
  PROCESS_REQUEST = 4,
  CREATE_RESPONSE = 8,
  PROCESS_FINISHED_RESPONSE = 16,
  PRESENDING_PROCESSING = 32
};

#endif
